// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvhhcwsgwjanfgggunmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aGhjd3Nnd2phbmZnZ2d1bm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjQ5NzMsImV4cCI6MjA2MTEwMDk3M30.1MYSN2tIqEiWMSvFbnclh29lCLt_9Kq6BW7jvWyGjDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);